### ISSUE TITLE
Missing an error handler

### ISSUE THREAD

**Issue by divineniiquaye** [leafsphp/leafMVC#13]
# Description

The application has no custom error handler for debugging. Instead, the application is left to PHP for error handling. I recently reported a bug described in issue #12, which goes to show that having an error handler is key.

# Motivation and context

The entire application system and every repository used under the @leaf organization has no tests and there's absolutely no way of debugging a crisis unless from PHP itself which is even hard sometimes to read and understand.

# Expected Behavior or Solution

There are several error handlers available for PHP, I recommend any of [Tracy](https://github.com/nette/tracy) or [Symfony Error Handler](https://github.com/symfony/error-handler), or [Filp Whoops](https://github.com/filp/whoops). Error handling helps in better and safer development.

**Comment by mychidarko** [comment]
Actually, the base package, [leaf](https://github.com/leafsphp/leaf) comes with default error pages for multiple purposes. But since they are loaded only when leaf is initialised, if the app fails to start without reaching leaf, then the leaf error page will not be displayed. This goes back to #12 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/26604242/142844424-90bcfd6a-0ca1-4a96-841f-a3268d83d943.png">
This is a screenshot of the dev error page

**Comment by mychidarko** [comment]
I hope this answers the question on the error handling. If you still feel the need to use your own error handler, you can use the `setErrorHandler` method.

```php
app()->setErrorHandler(function () {
  echo "You can do anything here";
});
```

You can view the full documentation on error handling with leaf [here](https://leafphp.dev/docs/routing/errors.html#handling-500)

**Comment by divineniiquaye** [comment]
> I hope this answers the question on the error handling. If you still feel the need to use your own error handler, you can use the `setErrorHandler` method.
> 
> ```
> app()->setErrorHandler(function () {
>   echo "You can do anything here";
> });
> ```
> 
> You can view the full documentation on error handling with leaf [here](https://leafphp.dev/docs/routing/errors.html#handling-500)

Great, I needed this.
